### ISSUE TITLE
Availability on PyPI

### ISSUE THREAD

**Issue by stefan6419846** [nightlark/swig-pypi#41]
When trying to use the installation instructions from the README (`pip install swig`), the package does not seem to be found. Looking up https://pypi.org/project/swig/ seems to indicate that there is no official package yet.

Is this correct? What is the current status of this project?

**Comment by nightlark** [comment]
Hi @stefan6419846, sorry for the delay (got sick among other things) -- I had hoped that SWIG version 4.1.0 would come out  soon (well nearly a year now), which adds support for building with CMake. That would resolve a number of issues related to building wheels from source for Windows and Apple Silicon Macs.

Since it has been quite a wait for 4.1.0 (and it is unclear it will come out soon), I went ahead and finished building wheels for an assortment of SWIG 3.x and 4.x versions, and uploaded them to PyPI, so `pip install swig` should work, listing it in a `requirements.txt` file, or including it in the list of packages for `build-system.requires` in a `pyproject.toml` file.

Let me know if you run into any issues, or need additional features added to the Python wrapper for your use case(s).

**Comment by stefan6419846** [comment]
Thanks for the explanations and providing some binaries. I just stumbled upon this project when looking for suitable ways to make *swig* available for semi-automated package builds. It appeared to be a possible replacement to avoid requiring root access for the actual build when using a virtual environment.

For now the system package approach works well enough. Nevertheless, this general status update is nice to have, given the fact that meanwhile two more users seem to have indicated interest in the current status as well.

I am going to close this issue, as the initial request has been resolved. If there are further issues arising from the usage (for example if I give it a try myself in the future), this should go to separate GitHub issues anyway.
